/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package feupw;

import com.gruposantorun.comprobantes.modelo.modelo.*;
import com.gruposantorun.comprobantes.modelo.modelo.notacredito.*;
import com.gruposantorun.comprobantes.seguridad.CertificadosSSL;
import com.gruposantorun.comprobantes.seguridad.Signer;
import com.gruposantorun.comprobantes.util.ClaveAcceso;
import com.gruposantorun.comprobantes.util.XMLUtil;

//--paquetes del online que se utilizan para recuperar la autorizacion
import com.gruposantorun.comprobantes.ws.AutorizacionComprobantesWS;
import com.gruposantorun.comprobantes.ws.VerificarExistenciaAutorizado;
import ec.gob.sri.comprobantes.ws.aut.Autorizacion;
import ec.gob.sri.comprobantes.ws.aut.RespuestaComprobante;

//--paquetes para la autorizacion de comprobantes off line en produccion
import com.gruposantorun.comprobantes.ws.produccion.off.EnvioComprobantesWSOFFPRO;
import com.gruposantorun.comprobantes.ws.produccion.off.VerificarDisponibilidadOFFPRO;

//--paquetes para la autorizacion de comprobantes off line en pruebas 
import com.gruposantorun.comprobantes.ws.pruebas.off.EnvioComprobantesWSOFFPRU;
import com.gruposantorun.comprobantes.ws.pruebas.off.VerificarDisponibilidadOFFPRU;

import java.io.*;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
//import javax.swing.//JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceException;

/**
 *
 * @author Progrmador3
 */
public class FEUPW_NCRE extends javax.swing.JFrame {

    boolean pasar = false;
    int contador = -1;
    Connection con = null;
    ResultSet rs = null;
    CallableStatement cst = null;
    String tipo = "";
    LeerSaiFact fac = new LeerSaiFact();
    VerificarExistenciaAutorizado ver = new VerificarExistenciaAutorizado();
    VerificarDisponibilidadOFFPRU exi_pru  = new VerificarDisponibilidadOFFPRU();
    VerificarDisponibilidadOFFPRO exi_pro  = new VerificarDisponibilidadOFFPRO();
    private static File archivo = null;
    private static FileWriter fichero = null;
    private static FileReader fr = null;
    private static BufferedReader br = null;
    private static PrintWriter escrive = null;
    String auxcod = "";
    String auxnum = "";
    String codemp = "";
    String codsuc = "";
    String tip = "";
    String cod_str = "";
    String num_str = "";
    Double cod = 0.0;
    Double num = 0.0;
    BigDecimal num_bd;
    BigDecimal cod_bd;
    ClaveAcceso clv = new ClaveAcceso();
    DefaultTableModel md1 = new DefaultTableModel();
    String nomclave = "";
    String fecAutorizacion = "";
    String numeAutorizacion = "";
    String estadoAutorizacion = "AUTORIZADO";
    String estado = "";
    String sqltipo = "";
    String tip_aplic = "";
    boolean save = false;
    boolean pasaAut = false;
    boolean procesamiento = false;
    boolean disponibilidad = false;
    boolean contingencia = false;
    boolean existeAutorizado = false;
    boolean obtenerAutorizado = false;
    boolean recibido = false;
    String Servidor_emp = "";
    String ambiente = "";
    String certificado = "";
    String clavecertificado = "";
    String urlwebService = "";
    String urlwebService1 = "";
    int buscar_aut = 0;
    boolean bandera = false;
    boolean band = false;
    boolean exfccompelec = false;
    String nomAmbiente = "";
    String reenviaSRI  ="0";

    String envio_compe ="";
    
    int     envioSRI     = 0;
    boolean recupera_aut = false;
    boolean enviaDoc     = false;

    public FEUPW_NCRE() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        primerPaso();
        procesarNotacredito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sucursal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipo_comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        factura = new javax.swing.JTextField();
        FACT_PROCESAR = new javax.swing.JButton();
        FACT_SALIR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        devolucion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nota de Credito");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ASCplus1.png"))); // NOI18N

        jLabel4.setText("Empresa:");

        empresa.setEditable(false);

        jLabel5.setText("sucursal:");

        sucursal.setEditable(false);

        jLabel3.setText("Tipo:");

        tipo_comp.setEditable(false);

        jLabel2.setText("Número:");

        factura.setEditable(false);
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });

        FACT_PROCESAR.setText("PROCESAR");
        FACT_PROCESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACT_PROCESARActionPerformed(evt);
            }
        });

        FACT_SALIR.setText("SALIR");
        FACT_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACT_SALIRActionPerformed(evt);
            }
        });

        jLabel6.setText("Factura:");

        devolucion.setEditable(false);
        devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipo_comp, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(sucursal)
                            .addComponent(empresa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FACT_PROCESAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FACT_SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(factura)
                    .addComponent(devolucion))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sucursal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(FACT_PROCESAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FACT_SALIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void primerPaso() {
        File f = new File("C:\\sai_win\\FEUPW.ini");
        String tipa = "";
        String emp = "";
        String suc = "";
        String num = "";
        String fact = "";
        String existe = "";
        if (f.exists()) {
            tipa = fac.getTipo();
            emp = fac.getEmpresa();
            suc = fac.getSucursal();
            num = fac.getNumero();
            fact = fac.getFactura();
            empresa.setText(emp);
            sucursal.setText(suc);
            tipo_comp.setText(tipa);
            devolucion.setText(num);
            factura.setText(fact);
        }
        existe = "SELECT COUNT(tipo) FROM FCCOMPELEC WITH(NOLOCK) "
                + " WHERE  TIPO=" + tipa
                + " AND    CODEMP=" + emp
                + " AND    CODSUC=" + suc
                + " AND    NUMERO_TRANS=" + num
                + " AND    NUMERO_FACT=" + fact;
        try {
            String cont = "";
            pruebanet bd = new pruebanet();
            con = bd.getConexion();
            PreparedStatement pstm = con.prepareStatement(existe);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                cont = rs.getString("CANTIDAD");
            }
            if (cont.isEmpty()) {
                cont = "0";
            }

            contador = Integer.parseInt(cont);
            System.out.println("conatdor" + cont);
            
            //mando a recuperar el envio sri de la tabla fccompelec
            envio_compe = "SELECT case when  isnull(envioSRI,'') = '' then '0' else envioSRI end AS envio FROM FCCOMPELEC WITH(NOLOCK) "
                    + " WHERE  TIPO=" + "'" + tipa + "'"
                    + " AND    CODEMP=" + emp
                    + " AND    CODSUC=" + suc
                    + " AND    NUMERO_TRANS=" + num
                    + " AND    NUMERO_FACT=" + fact;
            PreparedStatement pstmenvio = con.prepareStatement(envio_compe);
            ResultSet rsenvio = pstmenvio.executeQuery();
            while (rsenvio.next()) {
                reenviaSRI = rsenvio.getString("envio");
            }
            
            if ( (reenviaSRI == null) || (reenviaSRI.equals("")) ) {
                 reenviaSRI = "0";
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (Exception e) {
                }
            }
            if (con != null) {
                try {
                    con.close();
                } catch (Exception e) {
                }
            }
        }
        
        if (contador == 0) {
            exfccompelec = true;
        } else {
            exfccompelec = false;
        }

    }// fin de primer paso

    private void procesarNotacredito() {
        
        ParametrosExternos p = new ParametrosExternos();
        DecimalFormat df = new DecimalFormat("############");

        sqltipo = "SELECT TIP_APLIC FROM FCDOCFAC WITH(NOLOCK) "
                + " WHERE  CODEMP=" + empresa.getText().toString()
                + " AND    CODSUC=" + sucursal.getText().toString()
                + " AND    NUM_APLIC = " + factura.getText()
                + " AND NUMERO = " + devolucion.getText();
        try {
            pruebanet bd = new pruebanet();
            con = bd.getConexion();
            PreparedStatement pstm = con.prepareStatement(sqltipo);
            rs = pstm.executeQuery();
            while (rs.next()) {
                tip_aplic = rs.getString("TIP_APLIC");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.exit(0);
        } finally {
            if (rs != null) {
                try {
                } catch (Exception e) {
                }
            }
            if (con != null) {
                try {
                    System.out.println("conexion abierta");
                } catch (Exception e) {
                }
            }
        }

        try {
            fichero = new FileWriter("C:\\sai_win\\FEUPW.ini");
            escrive = new PrintWriter(fichero);
            for (int i = 0; i < 15; i++) {
                escrive.println("");
            }
            fichero.close();
        } catch (Exception e) {
        }
        cod = 0.0;
        num = 0.0;

        File dir = new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\");
        
        ////------------------------------      
        String clave_aux = "";
        boolean tranferencia = false;
        boolean envio1 = false;
        boolean envio2 = false;
        auxcod = this.factura.getText();
        auxnum = this.devolucion.getText();
        if (auxcod.equals("")) {
            cod = 0.0;
        }
        if (auxnum.equals("")) {
            num = 0.0;
        }
        
        tip = tip_aplic;
        codemp = this.empresa.getText();
        codsuc = this.sucursal.getText();
        cod_str = auxcod;
        num_str = auxnum;
        cod = Double.parseDouble(auxcod);
        num = Double.parseDouble(auxnum);
        cod_bd = new BigDecimal(auxcod);
        num_bd = new BigDecimal(auxnum);
        cod = Double.parseDouble(df.format(cod));
        num = Double.parseDouble(df.format(num));
        codemp = codemp.trim().toString();
        codsuc = codsuc.trim().toString();
        tip = tip.trim().toString();
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        p.Parametros(codemp, codsuc);
        Servidor_emp = p.getRutaXmlAutorizado().toString();
        ambiente = p.getTipoAmbiente().toString();
        certificado = p.getRutaCertificado();
        clavecertificado = p.getClaveAcceso();

        try {
            cst = con.prepareCall("{call buscar_comp_notaCredito_xml(?,?,?,?,?)}");
            cst.setString(1, codemp);
            cst.setString(2, codsuc);
            cst.setString(3, tip);
            cst.setDouble(4, num);
            cst.setDouble(5, cod);
            rs = cst.executeQuery();
            if (rs.next()) {
                com.gruposantorun.comprobantes.modelo.modelo.notacredito.NotaCredito nc = new com.gruposantorun.comprobantes.modelo.modelo.notacredito.NotaCredito();
                nc.setVersion("1.1.0");
                nc.setId("comprobante");
                ////JOptionPane.showMessageDialog(this, "Cliente Econtrado", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                //--------------------------------------------------------------------------------------
                clave_aux = clv.generarClaveAcceso(rs.getString("clave").toString().trim());
                if (clave_aux == null) {
                    //JOptionPane.showMessageDialog(this, "CLAVE ACCESO NO GENERADA, EL ARCHIVO NO SE PUEDE VALIDARSE", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    nomclave = "Factura_error" + rs.getString("secuencial").trim().toString();
                    pasar = false;
                    System.exit(0);

                } else {
                    nomclave = clave_aux;
                    pasar = true;
                }//if
                InfoTributaria it = new InfoTributaria();
                it.setAmbiente(rs.getString("ambiente").trim().toString());
                it.setTipoEmision(rs.getString("tipoEmision").trim().toString());
                it.setRazonSocial(rs.getString("razonsocial").trim().toString());
                it.setNombreComercial(rs.getString("nomComercial").trim().toString());
                it.setRuc(rs.getString("numeroruc").trim().toString());
                it.setClaveAcceso(clave_aux);
                it.setCodDoc(rs.getString("codDoc"));
                it.setEstab(rs.getString("estab").trim().toString());
                it.setPtoEmi(rs.getString("ptoEmi"));
                it.setSecuencial(rs.getString("secuencial").trim().toString());
                it.setDirMatriz(rs.getString("dirMatriz").trim().toString());
                nc.setInfoTributaria(it);
                InfoNotaCredito iff = new InfoNotaCredito();
                iff.setFechaEmision(rs.getString("fechaEmision").trim().toString());
                iff.setDirEstablecimiento(rs.getString("dirEstablecimiento").trim().toString());
                iff.setTipoIdentificacionComprador(rs.getString("tipoIdentificacionComprador").trim().toString());
                iff.setRazonSocialComprador(rs.getString("razonSocialComprador").trim().toString());
                iff.setIdentificacionComprador(rs.getString("identificacionComprador").trim().toString());
                iff.setContribuyenteEspecial(rs.getString("contribuyenteEspecial").trim().toString());
                iff.setObligadoContabilidad(rs.getString("obligadoContabilidad").trim().toString());
                iff.setRise(rs.getString("rise"));
                iff.setCodDocModificado(rs.getString("codDocModificado").trim().toString());
                iff.setNumDocModificado(rs.getString("numDocModificado").trim().toString());
                iff.setFechaEmisionDocSustento(rs.getString("fechaEmisionDocSustento").trim().toString());
                iff.setTotalSinImpuestos(new BigDecimal(rs.getString("totalSinImpuesto").trim().toString()));
                iff.setValorModificacion(new BigDecimal(rs.getString("valorModificado").trim().toString()));
                iff.setMoneda(rs.getString("moneda"));
                //----------------------------------------------------------------------IMPUESTOS
                TotalConImpuestos timp = new TotalConImpuestos();
                List<TotalImpuesto> lst_imp = new ArrayList();
                try {
                    cst = con.prepareCall("{call buscar_comp_impuestos_notaCredito_xml(?,?,?,?,?)}");
                    cst.setString(1, codemp);
                    cst.setString(2, codsuc);
                    cst.setString(3, tip);
                    cst.setDouble(4, num);
                    cst.setDouble(5, cod);
                    rs = cst.executeQuery();

                    while (rs.next()) {
                        Object[] fila1 = new Object[4];
                        for (int i = 0; i < 4; i++) {
                            fila1[i] = rs.getObject(i + 1);
                            //System.out.println(fila1[i]);
                        }// for
                        TotalImpuesto imp_1 = new TotalImpuesto();
                        imp_1.setCodigo(fila1[0].toString().trim());
                        imp_1.setCodigoPorcentaje(fila1[1].toString().trim());
                        imp_1.setBaseImponible(new BigDecimal(fila1[2].toString().trim()));
                        imp_1.setValor(new BigDecimal(fila1[3].toString().trim()));
                        lst_imp.add(imp_1);
                        timp.setTotalImpuesto(lst_imp);
                    }
                    iff.setTotalConImpuestos(timp);
                    iff.setMotivo("DEVOLUCIÓN");
                    nc.setInfoNotaCredito(iff);
                } catch (Exception e) {
                    System.out.println("Error: " + e.getMessage());
                }
                //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                //-----------------------------------------------------------------------DETALLE DE LA FACTURA
                Detalles dts = new Detalles();
                List<Detalle> detalle = new ArrayList();
                try {
//                                     //JOptionPane.showMessageDialog(this, "codemp: "+codemp+
//                                                "\n codsuc: "+codsuc+
//                                                "\n tipo: "+tip+
//                                                  "\n tipo: "+num+
//                                                "\n factura: "+cod , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    cst = con.prepareCall("{call buscar_detalle_notaCredito_xml(?,?,?,?,?)}");
                    cst.setString(1, codemp);
                    cst.setString(2, codsuc);
                    cst.setString(3, tip);
                    cst.setDouble(4, num);
                    cst.setDouble(5, cod);
                    rs = cst.executeQuery();
                    while (rs.next()) {
                        Object[] fila1 = new Object[13];
                        for (int i = 0; i < 13; i++) {
                            fila1[i] = rs.getObject(i + 1);
                            System.out.println(fila1[i]);
                        }// for
                        //md.addRow(fila1);
                        Detalle fd1 = new Detalle();

                        fd1.setCodigoInterno(fila1[0].toString().trim());
                        fd1.setCodigoAdicional(fila1[1].toString().trim());
                        fd1.setDescripcion(fila1[2].toString().trim());
                        fd1.setCantidad(new BigDecimal(fila1[3].toString().trim()));
                        fd1.setPrecioUnitario(new BigDecimal(fila1[4].toString().trim()));
                        fd1.setDescuento(new BigDecimal(fila1[5].toString().trim()));
                        fd1.setPrecioTotalSinImpuesto(new BigDecimal(fila1[6].toString().trim()));

                        List<DetAdicional> lsta = new ArrayList();
                        DetAdicional dea = new DetAdicional();
                        dea.setNombre("Vendedor");
                        dea.setValor(fila1[7].toString().trim());
                        lsta.add(dea);
                        fd1.setDetAdicional(lsta);

                        List<Impuesto> lstimp = new ArrayList();
                        Impuesto imp = new Impuesto();
                        imp.setCodigo(fila1[8].toString().trim());
                        imp.setCodigoPorcentaje(fila1[9].toString().trim());

                        imp.setTarifa(new BigDecimal(fila1[10].toString().trim()));
                        imp.setBaseImponible(new BigDecimal(fila1[11].toString().trim()));
                        imp.setValor(new BigDecimal(fila1[12].toString().trim()));
                        lstimp.add(imp);
                        fd1.setImpuesto(lstimp);
                        detalle.add(fd1);
                    }// while
                    dts.setDetalle(detalle);
                    nc.setDetalles(dts);
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                }// try 2
                //-----------------------------------------------------------------------
                InfoAdicional infad = new InfoAdicional();
                List<CampoAdicional> lstifa = new ArrayList();
                CampoAdicional cmpad = new CampoAdicional();
                cmpad.setNombre("Proveedor");
                cmpad.setValue("Grupo Santorun");
                lstifa.add(cmpad);
                infad.setCampoAdicional(lstifa);
                nc.setInfoAdicional(infad);
                //nc.setDetalle(detalle);
                //--------------------------------------------------------------------------------------
                  //--------------------------------------------------------------------------------------
                if (dir.exists()) {
                    XMLUtil.marshall(nc, "C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\" + nomclave + ".xml");
                    tranferencia = true;
                } else {
                    dir.mkdirs();
                    XMLUtil.marshall(nc, "C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\" + nomclave + ".xml");
                    tranferencia = true;
                }
                
                
            } else {
                //JOptionPane.showMessageDialog(this, "Cliente No Econtrado", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                tranferencia = false;
                System.exit(0);
            }
            cst.close();
            con.close();
            rs.close();
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(this, "Error: " +e.getMessage() , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Error: " + e.getMessage());
            System.exit(0);
        }
        
        /////------------------------------------------------ VALIDA EL XML GENERADO POR MEDIO DEL XSD
               if (tranferencia) {
                    File dirXSD = new File("C:\\xsd\\");
                    if (dirXSD.exists()) {
                        String mensajes = XMLUtil.validarXML(new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\" + nomclave + ".xml"), new File("C:\\xsd\\notaCredito.xsd"));
                        if (mensajes == null) {
                            tranferencia = true;
                        } else {
                            //JOptionPane.showMessageDialog(this, "El archivo no se pudo Validar: " + mensajes, "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                            tranferencia = false;
                            System.exit(0);
                        }//if
                    } else {
                        //JOptionPane.showMessageDialog(this, "La carpeta XSD para validar los comprobantes no exixte ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                        tranferencia = false;
                        System.exit(0);                     
                    }
                }     else {
                        //JOptionPane.showMessageDialog(this, "Nota Credito No Generada", "Aviso", //JOptionPane.INFORMATION_MESSAGE);              
                      }
        //////---------------------------------------------------------FIRMA ELECTRONICA
                if (tranferencia) {
                    File dirff = new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoFirmada\\");
                    if (dirff.exists()) {
                        Signer s = new Signer("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\" + nomclave + ".xml ", "C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoFirmada\\" + nomclave + ".xml");
                        s.parSignGen(certificado, clavecertificado);
                        try {
                            s.firmarFactura();
                            envio1 = true;
                        } catch (Exception e) {
                            //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                            envio1 = false;
                        }//trycatch
                    } else {
                        dirff.mkdirs();
                        Signer s = new Signer("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoGenerada\\" + nomclave + ".xml ", "C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoFirmada\\" + nomclave + ".xml");
                        s.parSignGen(certificado, clavecertificado);
                        try {
                            s.firmarFactura();
                            envio1 = true;
                        } catch (Exception e) {
                            //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                            envio1 = false;
                            System.exit(0);
                        }//trycatch
                    }// if si existe folio
                } else {
                    //JOptionPane.showMessageDialog(this, "Nota Credito No Paso la validacion XSD", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    System.exit(0);
                } 
        
        System.out.println("envio1 " + envio1);
       
        if (envio1) {         
            
            //---validamos el ambiente, conforme a eso se invoco los ws
            if (ambiente.equals("1")) {
            disponibilidad = exi_pru.existeConexionOFF(ambiente);
            }
            
            if (ambiente.equals("2")) {
            disponibilidad = exi_pro.existeConexionOFF(ambiente);
            }
            
            System.out.println("web service disponible " + disponibilidad);
                      
            //revisamos si el documento esta autorizado
            if (disponibilidad) {
                existeAutorizado = ver.VerificaWebServ(nomclave, ambiente);               
                if (existeAutorizado) {
                    System.out.println("documento autorizado ? " + existeAutorizado);
                    recupera_aut     = true;
                    envioSRI        = 1;
                }else {
                    System.out.println("documento autorizado ? " + existeAutorizado);
                    existeAutorizado = false;
                    enviaDoc = true;
                    recupera_aut = true;
                }
            }
            
            
            //------si el documento si tene autorizacion no entra al proceso de envio o tiene envioSRI en 0
            if (reenviaSRI.equals("0"))   {
                
                if (disponibilidad) {
                  try {
                    if (ambiente.equals("1")) {
                        System.out.println("entro a procesar autorizado ? " + existeAutorizado);
                        urlwebService = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl";
                        CertificadosSSL.instalarCertificados();
                        EnvioComprobantesWSOFFPRU wsa = new EnvioComprobantesWSOFFPRU(urlwebService.toString().trim());                      
                        com.gruposantorun.comprobantes.ws.pruebas.off.RespuestaSolicitud respuesta = wsa.enviarComprobante(new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoFirmada\\" + nomclave + ".xml"));
                        System.out.println("primero: " + respuesta.getEstado());
                        
                        if (respuesta.getEstado().equals("RECIBIDA")) {
                            //JOptionPane.showMessageDialog(this, "El documento ha sido enviada al SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                recibido = true;
                                envioSRI = 1;              
                            } else {
                                recibido = false;
                        
                            if (respuesta.getEstado().equals("DEVUELTA")) {
                                if (existeAutorizado) {  
                                    envioSRI = 1;
                                    reenviaSRI = "1";
                                }
                                else
                                {
                                    //JOptionPane.showMessageDialog(this, "El documento no ha sido recibida por el SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                    envioSRI = 0;
                                    List<com.gruposantorun.comprobantes.ws.pruebas.off.Comprobante> lst = respuesta.getComprobantes().getComprobante();
                                    System.out.println("ichi" + lst.isEmpty() );

                                        for (com.gruposantorun.comprobantes.ws.pruebas.off.Comprobante comprobante : lst) {
                                        List<com.gruposantorun.comprobantes.ws.pruebas.off.Mensaje> lstMensaje = comprobante.getMensajes().getMensaje();

                                            for (com.gruposantorun.comprobantes.ws.pruebas.off.Mensaje mensaje : lstMensaje) {
                                                if (mensaje.getMensaje().equals("CLAVE DE ACCESO EN PROCESAMIENTO")) {
                                                    //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                     //   + "\n Mensage: " + mensaje.getMensaje()
                                                     //   + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                    //    + "\n Generación de contingencia...",
                                                    //    "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                    envioSRI = 0;
                                                } else {
                                                    if (mensaje.getMensaje().equals("CLAVE ACCESO REGISTRADA")) {
                                                        envioSRI = 1;
                                                    } else {
                                                        System.out.println("estado: " + respuesta.getEstado());
                                                        System.out.println("identificador: " + mensaje.getIdentificador());
                                                        System.out.println("tipo: " + mensaje.getTipo()) ;
                                                        System.out.println("infoad: " + mensaje.getInformacionAdicional()) ;
                                                        //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                          //  + "\n Mensage: " + mensaje.getMensaje()
                                                        //    + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                       //     + "\n Generación de contingencia...",
                                                        //    "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                        envioSRI = 0;
                                                    } // fin de la clave en procesamiento
                                                } // IF
                                            }//for
                                        }//for
                                    }//fin de else autorizado
                                }// fin de devuelta
                            }// fin de recibida
                    }
                    if (ambiente.equals("2")) {
                        
                        urlwebService = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl";
                        CertificadosSSL.instalarCertificados();
                        EnvioComprobantesWSOFFPRO wsa = new EnvioComprobantesWSOFFPRO(urlwebService.toString().trim());                      
                        com.gruposantorun.comprobantes.ws.produccion.off.RespuestaSolicitud respuesta = wsa.enviarComprobante(new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoFirmada\\" + nomclave + ".xml"));
                        System.out.println("primero: " + respuesta.getEstado());
                        
                        if (respuesta.getEstado().equals("RECIBIDA")) {
                            //JOptionPane.showMessageDialog(this, "El documento ha sido enviada al SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                recibido = true;
                                envioSRI = 1;              
                            } else {
                                recibido = false;
                        
                            if (respuesta.getEstado().equals("DEVUELTA")) {
                                if (existeAutorizado) {  
                                    envioSRI = 1;
                                    reenviaSRI = "1";
                                }
                                else
                                {
                                    //JOptionPane.showMessageDialog(this, "El documento no ha sido recibida por el SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                    envioSRI = 0;
                                    List<com.gruposantorun.comprobantes.ws.produccion.off.Comprobante> lst = respuesta.getComprobantes().getComprobante();
                                    System.out.println("ichi" + lst.isEmpty() );

                                        for (com.gruposantorun.comprobantes.ws.produccion.off.Comprobante comprobante : lst) {
                                        List<com.gruposantorun.comprobantes.ws.produccion.off.Mensaje> lstMensaje = comprobante.getMensajes().getMensaje();

                                            for (com.gruposantorun.comprobantes.ws.produccion.off.Mensaje mensaje : lstMensaje) {
                                                if (mensaje.getMensaje().equals("CLAVE DE ACCESO EN PROCESAMIENTO")) {
                                                    //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                               //     + "\n Mensage: " + mensaje.getMensaje()
                                               //     + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                 //   + "\n Generación de contingencia...",
                                                //    "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                    envioSRI = 0;
                                                } else {
                                                    if (mensaje.getMensaje().equals("CLAVE ACCESO REGISTRADA")) {
                                                        envioSRI = 1;
                                                    } else {
                                                        System.out.println("estado: " + respuesta.getEstado());
                                                        System.out.println("identificador: " + mensaje.getIdentificador());
                                                        System.out.println("tipo: " + mensaje.getTipo()) ;
                                                        System.out.println("infoad: " + mensaje.getInformacionAdicional()) ;
                                                        //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                     //   + "\n Mensage: " + mensaje.getMensaje()
                                                    //    + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                     //   + "\n Generación de contingencia...",
                                                    //    "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                        envioSRI = 0;
                                                    } // fin de la clave en procesamiento
                                                } // IF
                                            }//for
                                        }//for
                                    }//fin de else autorizado
                                }// fin de devuelta
                            }// fin de recibida
                    }
                    
                    } catch (MalformedURLException ex) {
                        //JOptionPane.showMessageDialog(this, "ENVIO(MalformedURLException) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nDocumento no generado... ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                        Logger.getLogger(FEUPW_NCRE.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (WebServiceException ex) {
                        //JOptionPane.showMessageDialog(this, "ENVIO(WebServiceException) \nSin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nDocumento no generado... ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                        Logger.getLogger(FEUPW_NCRE.class.getName()).log(Level.SEVERE, null, ex);
                    }// fin try catch  
                }//
                
            }
 
            }// fin de ENVIO 1
        
        //----------------------si el documento esta autorizado manda a recuperar la autorizacion
        if (reenviaSRI.equals("1"))   {
            
            File ret_aut = new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoAutorizada\\");
            File ret_no_aut = new File("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoNoAutorizada\\");
            if (ambiente.equals("1")) {
                urlwebService1 = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl";
            }
            if (ambiente.equals("2")) {
                urlwebService1 = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl";
            }
            try {
                CertificadosSSL.instalarCertificados();
                List<String> lst_at = new ArrayList();
                AutorizacionComprobantesWS ws = new AutorizacionComprobantesWS(urlwebService1.toString().trim());
                RespuestaComprobante respuesta = ws.autorizarComprobante(nomclave);
                List<Autorizacion> lstAutorizacion = respuesta.getAutorizaciones().getAutorizacion();
                int contador = 0;
                int tam = lstAutorizacion.size();
                for (Autorizacion autorizacion : lstAutorizacion) {
                    try {
                        A aut = new A();
                        if (autorizacion.getEstado().equals("AUTORIZADO")) {
                            bandera = true;
                            band = true;
                        } 
                        contador++;
                        if (bandera && band) {
                            band = false;
                            aut.setComprobante("<![CDATA[" + autorizacion.getComprobante() + "]]>");
                            aut.setEstado(autorizacion.getEstado());
                            Calendar calendar = autorizacion.getFechaAutorizacion().toGregorianCalendar();
                            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");//yyyy/MM/dd
                            String fechaAutorizacion = sdf.format(calendar.getTime());
                            //--
                            if (ambiente.equals("1")) {
                                nomAmbiente = "PRUEBAS";
                            }

                            if (ambiente.equals("2")) {
                                nomAmbiente = "PRODUCCION";
                            }
                            aut.setFechaAutorizacion(fechaAutorizacion);
                            aut.setMensajes(autorizacion.getMensajes());
                            aut.setAmbiente(nomAmbiente);
                            aut.setNumeroAutorizacion(autorizacion.getNumeroAutorizacion());
                            //
                            if (aut.getEstado().equals(estadoAutorizacion)) {
                                fecAutorizacion = aut.getFechaAutorizacion();
                                numeAutorizacion = aut.getNumeroAutorizacion();
                                estado = aut.getEstado();
                                save = true;
                                envio2 = true;
                                buscar_aut++;
                            } 
                            
                            JAXBContext jc = JAXBContext.newInstance(A.class);
                            Marshaller marshaller = jc.createMarshaller();
                            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
                            marshaller.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
                            //-------------------------------------------------------------
                            if (ret_aut.exists()) {
                                Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoAutorizada\\" + nomclave + ".xml");
                                writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                writer.close();

                            } else {
                                ret_aut.mkdirs();
                                Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoAutorizada\\" + nomclave + ".xml");
                                writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                writer.close();
                            }
                            /////////////////////////////////////////////////////////////////////
                            if (estado.equals("AUTORIZADO")) {
                                try {
                                    File file_server = new File(Servidor_emp);
                                    if (file_server.exists()) {
                                        Writer writer = new FileWriter(Servidor_emp + "\\" + nomclave + ".xml");
                                        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                        marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                        writer.close();
                                    } else {
                                        file_server.mkdirs();
                                        Writer writer = new FileWriter(Servidor_emp + "\\" + nomclave + ".xml");
                                        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                        marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                        writer.close();
                                    }
                                } catch (Exception ex) {
                                }// catch ex  
                            }
                        } else {
                            //JOptionPane.showMessageDialog(this, "El documento no ha sido autorizado revisar el XML en la ruta: " + ret_no_aut , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                            if (!bandera && contador == tam) {
                                aut.setComprobante("<![CDATA[" + autorizacion.getComprobante() + "]]>");
                                aut.setEstado(autorizacion.getEstado());
                                Calendar calendar = autorizacion.getFechaAutorizacion().toGregorianCalendar();
                                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");//yyyy/MM/dd
                                String fechaAutorizacion = sdf.format(calendar.getTime());
                                //--
                                if (ambiente.equals("1")) {
                                    nomAmbiente = "PRUEBAS";
                                }

                                if (ambiente.equals("2")) {
                                    nomAmbiente = "PRODUCCION";
                                }
                                aut.setFechaAutorizacion(fechaAutorizacion);
                                aut.setMensajes(autorizacion.getMensajes());
                                aut.setAmbiente(nomAmbiente);
                                aut.setNumeroAutorizacion(autorizacion.getNumeroAutorizacion());
                                //
                                if (aut.getEstado().equals(estadoAutorizacion)) {
                                    fecAutorizacion = aut.getFechaAutorizacion();
                                    numeAutorizacion = aut.getNumeroAutorizacion();
                                    estado = aut.getEstado();
                                    save = true;
                                    envio2 = true;
                                    buscar_aut++;
                                } 
                                
                                JAXBContext jc = JAXBContext.newInstance(A.class);
                                Marshaller marshaller = jc.createMarshaller();
                                marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
                                marshaller.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
                                //-------------------------------------------------------------
                                if (ret_no_aut.exists()) {
                                    Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoNoAutorizada\\" + nomclave + ".xml");
                                    writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                    marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                    writer.close();
                                } else {
                                    ret_no_aut.mkdirs();
                                    Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\NOTACREDITO\\notaCreditoNoAutorizada\\" + nomclave + ".xml");
                                    writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                    marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                    writer.close();
                                }
                                /////////////////////////////////////////////////////////////////////// 
                            }// no autorizado
                        }// bandera 
                    } catch (Exception ex) {
                        //JOptionPane.showMessageDialog(this, "ENVIO(Exception) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nDocumento no generado..!", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    }//fin del try catch
                }// fin de for
            } catch (Exception ex) {
                //JOptionPane.showMessageDialog(this, "ENVIO(Exception) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nDocumento no generado..!", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
            }
        }//fin de obtener
        
        //---------------------------hacemos el insert para el fccompelec
        save = true;
        if (save) {
            try {
                pruebanet bd = new pruebanet();
                con = bd.getConexion();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            try {
                cst = con.prepareCall("{call buscar_insertar_notaCredito_xml(?,?,?,?,?,?,?,?,?,?,?)}");
                cst.setString(1, codemp);
                cst.setString(2, codsuc);
                cst.setString(3, "DE");
                cst.setBigDecimal(4, num_bd);
                cst.setBigDecimal(5, cod_bd);
                cst.setString(6, nomclave);
                cst.setString(7, nomclave);
                cst.setString(8, fecAutorizacion);
                cst.setString(9, estado);
                cst.setLong(10, 2);
                cst.setLong(11,envioSRI);
                rs = cst.executeQuery();
                if (rs == null) {
                }
                cst.close();
                con.close();
                envio2 = true;
                FACT_SALIR.setEnabled(true);
            } catch (Exception e) {
            }
        }

    System.exit(0);
    }

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturaActionPerformed

    private void FACT_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACT_SALIRActionPerformed
        this.dispose();
    }//GEN-LAST:event_FACT_SALIRActionPerformed

    private void devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devolucionActionPerformed

    private void FACT_PROCESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACT_PROCESARActionPerformed
        
    }//GEN-LAST:event_FACT_PROCESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FEUPW_NCRE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FACT_PROCESAR;
    private javax.swing.JButton FACT_SALIR;
    private javax.swing.JTextField devolucion;
    private javax.swing.JTextField empresa;
    private javax.swing.JTextField factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sucursal;
    private javax.swing.JTextField tipo_comp;
    // End of variables declaration//GEN-END:variables
}
