/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package feupw;

import com.gruposantorun.comprobantes.modelo.modelo.*;
import com.gruposantorun.comprobantes.modelo.modelo.factura.FacturaDetalle;
import com.gruposantorun.comprobantes.modelo.modelo.factura.InfoFactura;
import com.gruposantorun.comprobantes.modelo.modelo.factura.TotalImpuesto;
import com.gruposantorun.comprobantes.seguridad.CertificadosSSL;
import com.gruposantorun.comprobantes.seguridad.Signer;
import com.gruposantorun.comprobantes.util.ClaveAcceso;
import com.gruposantorun.comprobantes.util.ValidaCampo;
import com.gruposantorun.comprobantes.util.XMLUtil;

//--paquetes del online que se utilizan para recuperar la autorizacion
import com.gruposantorun.comprobantes.ws.AutorizacionComprobantesWS;
import com.gruposantorun.comprobantes.ws.VerificarExistenciaAutorizado;
import ec.gob.sri.comprobantes.ws.aut.Autorizacion;
import ec.gob.sri.comprobantes.ws.aut.RespuestaComprobante;

//--paquetes para la autorizacion de comprobantes off line en produccion
import com.gruposantorun.comprobantes.ws.produccion.off.EnvioComprobantesWSOFFPRO;
import com.gruposantorun.comprobantes.ws.produccion.off.VerificarDisponibilidadOFFPRO;

//--paquetes para la autorizacion de comprobantes off line en pruebas 
import com.gruposantorun.comprobantes.ws.pruebas.off.EnvioComprobantesWSOFFPRU;
import com.gruposantorun.comprobantes.ws.pruebas.off.VerificarDisponibilidadOFFPRU;

import java.io.*;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.sql.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceException;
/**
 *
 * @author Washington Carrillo
 */
public class FEUPW_FACT extends javax.swing.JFrame {
    
    LeerSaiFact fac = new LeerSaiFact();
    VerificarExistenciaAutorizado ver      = new VerificarExistenciaAutorizado();
    VerificarDisponibilidadOFFPRU exi_pru  = new VerificarDisponibilidadOFFPRU();
    VerificarDisponibilidadOFFPRO exi_pro  = new VerificarDisponibilidadOFFPRO();
    ClaveAcceso clv = new ClaveAcceso();
    DefaultTableModel md1 = new DefaultTableModel();
    
    boolean pasar = false;
    Connection con = null;
    ResultSet rs = null;
    CallableStatement cst = null;
    int contador = -1;
    String tipo = "";
    
    private static File archivo = null;
    private static FileWriter fichero = null;
    private static FileReader fr = null;
    private static BufferedReader br = null;
    private static PrintWriter escrive = null;
    String hfactura = "";
    String auxcod = "";
    String auxnum = "";
    String codemp = "";
    String codsuc = "";
    String tip = "";
    Double cod = 0.0;
    Double num = 0.0;
    
    String nomclave = "";
    String fecAutorizacion = "";
    String numeAutorizacion = "";
    String estadoAutorizacion = "AUTORIZADO";
    String estado = "";
    String estado_no = "";
    boolean save = false;
    boolean pasaAut = false;
    boolean procesamiento = false;
    boolean disponibilidad = false;
    boolean contingencia = false;
    boolean existeAutorizado = false;
    boolean obtenerAutorizado = false;
    boolean recibido = false;
    Date date;
    String identificador = "";
    String mensaje = "";
    String informacionAdicional = "";
    String tipo_m = "";
    String Servidor_emp = "";
    String ambiente = "";
    String certificado = "";
    String clavecertificado = "";
    String urlwebService = "";
    String urlwebService1 = "";
    String ordenComp = "";
    String correo = "";
    String aux_comprobante = "";
    String[] auxserv = {};
    int buscar_aut = 0;
    boolean bandera = false;
    boolean band = false;
    boolean exfccompelec = false;
    String nomAmbiente = "";
    String  reenviaSRI   = "0";
    
    int     envioSRI     = 0;
    boolean recupera_aut = false;
    boolean enviaDoc     = false;
/////////////////////////////////////////////////////////////////////////////

    public FEUPW_FACT() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        primerPaso();
        procesarFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sucursal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipo_comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        FACT_PROCESAR = new javax.swing.JButton();
        FACT_SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación Electrónica");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ASCplus1.png"))); // NOI18N

        jLabel4.setText("Empresa:");

        empresa.setEditable(false);

        jLabel5.setText("sucursal:");

        sucursal.setEditable(false);

        jLabel3.setText("Tipo:");

        tipo_comp.setEditable(false);

        jLabel2.setText("Codigo:");

        numero.setEditable(false);
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        FACT_PROCESAR.setText("PROCESAR");
        FACT_PROCESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACT_PROCESARActionPerformed(evt);
            }
        });

        FACT_SALIR.setText("SALIR");
        FACT_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACT_SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipo_comp, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(sucursal)
                            .addComponent(empresa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FACT_PROCESAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FACT_SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(numero))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sucursal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FACT_PROCESAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FACT_SALIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void primerPaso() {
        File f = new File("C:\\sai_win\\FEUPW.ini");
        String tipa = "";
        String emp = "";
        String suc = "";
        String num = "";
        String fact = "";
        String existe = "";
        String envio_compe = "";
        if (f.exists()) {
            tipa = fac.getTipo();
            emp = fac.getEmpresa();
            suc = fac.getSucursal();
            num = fac.getNumero();
            fact = fac.getFactura();
            empresa.setText(emp);
            sucursal.setText(suc);
            tipo_comp.setText(tipa);
            numero.setText(num);
            hfactura = fact;
        }
        try {
            String cont = "";
            existe = "SELECT COUNT(tipo) AS CANTIDAD FROM FCCOMPELEC WITH(NOLOCK) "
                    + " WHERE  TIPO=" + "'" + tipa + "'"
                    + " AND    CODEMP=" + emp
                    + " AND    CODSUC=" + suc
                    + " AND    NUMERO_TRANS=" + num
                    + " AND    NUMERO_FACT=" + fact;
            pruebanet bd = new pruebanet();
            con = bd.getConexion();
            PreparedStatement pstm = con.prepareStatement(existe);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                cont = rs.getString("CANTIDAD");
            }
            contador = Integer.parseInt(cont);
            System.out.println("cantidad " + contador);
            
                       //mando a recuperar el envio sri de la tabla fccompelec
            envio_compe = "SELECT case when  isnull(envioSRI,'') = '' then '0' else envioSRI end AS envio FROM FCCOMPELEC WITH(NOLOCK) "
                    + " WHERE  TIPO=" + "'" + tipa + "'"
                    + " AND    CODEMP=" + emp
                    + " AND    CODSUC=" + suc
                    + " AND    NUMERO_TRANS=" + num
                    + " AND    NUMERO_FACT=" + fact;
            PreparedStatement pstmenvio = con.prepareStatement(envio_compe);
            ResultSet rsenvio = pstmenvio.executeQuery();
            while (rsenvio.next()) {
                reenviaSRI = rsenvio.getString("envio");
            }
            
            if ( (reenviaSRI == null) || (reenviaSRI.equals("")) ) {
                 reenviaSRI = "0";
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
            contingencia = true;
            obtenerAutorizado = false;
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (Exception e) {
                }
            }
            if (con != null) {
                try {
                    con.close();
                } catch (Exception e) {
                }
            }
        }
        
        if (contador == 0) {
            exfccompelec = true;
            System.out.println("existe en compelec?" + exfccompelec);
        } else {
            exfccompelec = false;
            System.out.println("existe en compelec?" + exfccompelec);
        }
    }
    
    

    private void procesarFactura() {
        cod = 0.0;
        num = 0.0;
        File dir = new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\");
        String clave_aux = "";
        String auxfecha = "";
        String nuevo = "";
        String[] fec;
        boolean tranferencia = false;
        boolean envio1 = false;
        boolean envio2 = false;
        FACT_SALIR.setEnabled(false);
        FACT_PROCESAR.setEnabled(false);
        // la conexion 
        ParametrosExternos p = new ParametrosExternos();
        ValidaCampo vc = new ValidaCampo();
        try {
            pruebanet bd = new pruebanet();
            con = bd.getConexion();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            tranferencia = false;
            contingencia = true;
            obtenerAutorizado = false;
        }// fin del try
        // borra los datos del archivo puente
        try {
            fichero = new FileWriter("C:\\sai_win\\FEUPW.ini");
            escrive = new PrintWriter(fichero);
            for (int i = 0; i < 15; i++) {
                escrive.println("");
            }
            fichero.close();
        } catch (Exception e) {
        }
        auxcod = this.numero.getText();
        ordenComp = "";
        if (auxcod.equals("")) {
            cod = 0.0;
        }
        if (auxnum.equals("")) {
            num = 0.0;
        }
        tip = this.tipo_comp.getText();
        codemp = this.empresa.getText();
        codsuc = this.sucursal.getText();
        if (auxcod.isEmpty()) {
            tranferencia = false;
            contingencia = true;
            obtenerAutorizado = false;
        }
        if ( hfactura.isEmpty() ) {
            tranferencia = false;
            contingencia = true;
            obtenerAutorizado = false;
        }

        cod = Double.parseDouble(auxcod);
        num = Double.parseDouble(hfactura);
        codemp = codemp.trim().toString();
        codsuc = codsuc.trim().toString();
        tip = tip.trim().toString();
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        p.Parametros(codemp, codsuc);
        Servidor_emp = p.getRutaXmlAutorizado().toString();
        ambiente = p.getTipoAmbiente().toString();
        certificado = p.getRutaCertificado();
        clavecertificado = p.getClaveAcceso();
       //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        try {
            cst = con.prepareCall("{call buscar_comp_facturaElectronica_xml(?,?,?,?)}");
            cst.setString(1, codemp);
            cst.setString(2, codsuc);
            cst.setString(3, tip);
            cst.setDouble(4, cod);
            rs = cst.executeQuery();
            if (rs.next()) {
                com.gruposantorun.comprobantes.modelo.modelo.factura.Factura f = new com.gruposantorun.comprobantes.modelo.modelo.factura.Factura();
                f.setVersion("1.1.0");
                f.setId("comprobante");
                ////JOptionPane.showMessageDialog(this, "Cliente Econtrado", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                //--------------------------------------------------------------------------------------
                clave_aux = clv.generarClaveAcceso(rs.getString("clave").toString().trim());
                if (clave_aux == null) {
                    //JOptionPane.showMessageDialog(this, "CLAVE ACCESO NO GENERADA, EL ARCHIVO NO SE PUEDE VALIDARSE", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    nomclave = "Factura_error" + rs.getString("secuencial").trim().toString();
                    pasar = false;
                    System.exit(0);

                } else {
                    nomclave = clave_aux;
                    pasar = true;
                }//if
                InfoTributaria it = new InfoTributaria();
                it.setAmbiente(rs.getString("ambiente").trim().toString());
                it.setTipoEmision(rs.getString("tipoEmision").trim().toString());
                it.setRazonSocial(rs.getString("razonsocial").trim().toString());
                it.setNombreComercial(rs.getString("nomComercial").trim().toString());
                it.setRuc(rs.getString("numeroruc").trim().toString());
                it.setClaveAcceso(clave_aux);
                it.setCodDoc("01");
                it.setEstab(rs.getString("estab").trim().toString());
                it.setPtoEmi(rs.getString("ptoEmi"));
                it.setSecuencial(rs.getString("secuencial").trim().toString());
                it.setDirMatriz(rs.getString("direccion").trim().toString());
                f.setInfoTributaria(it);

                InfoFactura iff = new InfoFactura();
                auxfecha = rs.getString("fechaEmision").trim().toString();
                auxfecha = auxfecha.substring(0, 10);
                fec = auxfecha.split("-");
                nuevo = fec[2] + "/" + fec[1] + "/" + fec[0];
                iff.setFechaEmision(nuevo);
                iff.setDirEstablecimiento(rs.getString("dirEstablecimiento").trim().toString());
                iff.setContribuyenteEspecial(rs.getString("contribuyenteEspecial").trim().toString());
                iff.setObligadoContabilidad(rs.getString("obligadoContabilidad").trim().toString());
                iff.setTipoIdentificacionComprador(rs.getString("TIPIDCLIENTE").trim().toString());
                iff.setRazonSocialComprador(rs.getString("razonSocialComprador").trim().toString());
                iff.setIdentificacionComprador(rs.getString("IDCLIENTE").trim().toString());
                iff.setTotalSinImpuestos(new BigDecimal(rs.getString("totalSinImpuestos").trim().toString()));
                iff.setTotalDescuento(new BigDecimal(rs.getString("totalDescuento").trim().toString()));
                iff.setPropina(new BigDecimal("0.00"));
                iff.setImporteTotal(new BigDecimal(rs.getString("importeTotal").trim().toString()));
                iff.setMoneda("Dolar");
//                ordenComp = rs.getString("grnomrazsoc1").trim().toString();
//                correo = rs.getString("NOM2").trim().toString();
                List<TotalImpuesto> lst = new ArrayList<>();
                try {
                    cst = con.prepareCall("{call buscar_comp_impuestos_factura_xml(?,?,?,?)}");
                    cst.setString(1, codemp);
                    cst.setString(2, codsuc);
                    cst.setString(3, tip);
                    cst.setDouble(4, cod);
                    rs = cst.executeQuery();
                    while (rs.next()) {
                        Object[] fila1 = new Object[4];
                        for (int i = 0; i < 4; i++) {
                            fila1[i] = rs.getObject(i + 1);
                        }// for
                        TotalImpuesto t1 = new TotalImpuesto();
                        t1.setCodigo(fila1[0].toString().trim());
                        t1.setCodigoPorcentaje(fila1[1].toString().trim());
                        t1.setBaseImponible(new BigDecimal(fila1[2].toString().trim()));
                        t1.setValor(new BigDecimal(fila1[3].toString().trim()));
                        lst.add(t1);
                    }
                    iff.setTotalImpuesto(lst);
                    f.setInfoFactura(iff);
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(this, "ERROR SP IMPUESTO " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("Error: " + e.getMessage());
                }
                //-----------------------------------------------------------------------DETALLE DE LA FACTURA
                List<FacturaDetalle> detalle = new ArrayList();
                try {
                    cst = con.prepareCall("{call buscar_detalle_facturaElectronica_xml(?,?,?,?)}");
                    cst.setString(1, codemp);
                    cst.setString(2, codsuc);
                    cst.setString(3, tip);
                    cst.setDouble(4, cod);
                    rs = cst.executeQuery();
                    while (rs.next()) {
                        Object[] fila1 = new Object[12];
                        for (int i = 0; i < 12; i++) {
                            fila1[i] = rs.getObject(i + 1);
                        }// for
                        //md.addRow(fila1);
                        FacturaDetalle fd1 = new FacturaDetalle();
                        fd1.setCodigoPrincipal(fila1[0].toString().trim());
                        fd1.setCodigoAuxiliar(fila1[1].toString().trim());
                        fd1.setDescripcion(fila1[2].toString().trim());
                        fd1.setCantidad(new BigDecimal(fila1[3].toString().trim()));
                        fd1.setPrecioUnitario(new BigDecimal(fila1[4].toString().trim()));
                        fd1.setDescuento(new BigDecimal(fila1[5].toString().trim()));
                        fd1.setPrecioTotalSinImpuesto(new BigDecimal(fila1[6].toString().trim()));
                        List<DetAdicional> lsta = new ArrayList();
                        DetAdicional dea = new DetAdicional();
                        dea.setNombre("aux");
                        dea.setValor("0");
                        lsta.add(dea);
                        fd1.setDetAdicional(lsta);
                        List<Impuesto> lstimp = new ArrayList();
                        Impuesto imp = new Impuesto();
                        imp.setCodigo(fila1[7].toString().trim());
                        imp.setCodigoPorcentaje(fila1[8].toString().trim());
                        imp.setTarifa(new BigDecimal(fila1[9].toString().trim()));
                        imp.setBaseImponible(new BigDecimal(fila1[10].toString().trim()));
                        imp.setValor(new BigDecimal(fila1[11].toString().trim()));
                        lstimp.add(imp);
                        fd1.setImpuesto(lstimp);
                        detalle.add(fd1);
                    }// while
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    System.exit(0);
                }// try 2
                //-----------------------------------------------------------------------
                InfoAdicional infad = new InfoAdicional();
                List<CampoAdicional> lstifa = new ArrayList();
                CampoAdicional cmpad1 = new CampoAdicional();
                cmpad1.setNombre("Proveedor");
                cmpad1.setValue("Grupo Santorun");
                lstifa.add(cmpad1);
                infad.setCampoAdicional(lstifa);
                f.setInfoAdicional(infad);
                f.setDetalle(detalle);
                 //--------------------------------------------------------------------------------------
                if (dir.exists()) {
                    XMLUtil.marshall(f, "C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\" + nomclave + ".xml");
                    tranferencia = true;
                } else {
                    dir.mkdirs();
                    XMLUtil.marshall(f, "C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\" + nomclave + ".xml");
                    tranferencia = true;
                }
            } else {
                //JOptionPane.showMessageDialog(this, "Cliente No Econtrado", "Aviso", //JOptionPane.ERROR_MESSAGE);
                tranferencia = false;
                contingencia = true;
                obtenerAutorizado = false;
            }
            cst.close();
            con.close();
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.ERROR_MESSAGE);
            tranferencia = false;
            contingencia = true;
            obtenerAutorizado = false;
        } // fin de la generacion del xml
        
        /////------------------------------------------------ VALIDA EL XML GENERADO POR MEDIO DEL XSD
        if (tranferencia) {
            File dirXSD = new File("C:\\xsd\\");
            if (dirXSD.exists()) {
                String mensajes = XMLUtil.validarXML(new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\" + nomclave + ".xml"), new File("C:\\xsd\\factura.xsd"));
                if (mensajes == null) {
                    tranferencia = true;
                } else {
                    //JOptionPane.showMessageDialog(this, "El archivo no se pudo Validar: " + mensajes, "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    tranferencia = false;
                    System.exit(0);

                }//if
            } else {
                //JOptionPane.showMessageDialog(this, "La carpeta XSD para validar los comprobantes no exixte ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                tranferencia = false;
                System.exit(0);
            }// fin dirxsd

        } else {
            //JOptionPane.showMessageDialog(this, "Factura No Generada", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        } // VALIDA EL XML fin de tranferencia
        
        
        //////---------------------------------------------------------FIRMA ELECTRONICA
        if (tranferencia) {
            File dirff = new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaFirmada\\");
            if (dirff.exists()) {
                Signer s = new Signer("C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\" + nomclave + ".xml ", "C:\\ComprobanteElectronicos\\FACTURA\\FacturaFirmada\\" + nomclave + ".xml");
                s.parSignGen(certificado, clavecertificado);
                try {
                    s.firmarFactura();
                    envio1 = true;
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    envio1 = false;
                    System.exit(0);
                }//trycatch
            } else {
                dirff.mkdirs();
                Signer s = new Signer("C:\\ComprobanteElectronicos\\FACTURA\\FacturaGenerada\\" + nomclave + ".xml ", "C:\\ComprobanteElectronicos\\FACTURA\\FacturaFirmada\\" + nomclave + ".xml");
                s.parSignGen(certificado, clavecertificado);
                try {
                    s.firmarFactura();

                    envio1 = true;
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    envio1 = false;
                    System.exit(0);
                }//trycatch
            }// if si existe folio
        } else {
            //JOptionPane.showMessageDialog(this, "Factura No Paso la validacion XSD", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
            envio1 = false;
            System.exit(0);
        } // LA FIRMA DIGITAL
        
        //////--------------------------------------------ENVIO AL SRI A LOS DIFERENTES WEB SERVICES
        System.out.println("envio1 " + envio1);
        if (envio1) {
            
            //---validamos el ambiente, conforme a eso se invoco los ws
            if (ambiente.equals("1")) {
            disponibilidad = exi_pru.existeConexionOFF(ambiente);
            }
            
            if (ambiente.equals("2")) {
            disponibilidad = exi_pro.existeConexionOFF(ambiente);
            }
            
            System.out.println("web service disponible " + disponibilidad);           
            //revisamos si el documento esta autorizado
            if (disponibilidad) {
                existeAutorizado = ver.VerificaWebServ(nomclave, ambiente);               
                if (existeAutorizado) {
                    System.out.println("documento autorizado ? " + existeAutorizado);
                    recupera_aut     = true;
                    envioSRI        = 1;
                }else {
                    System.out.println("documento autorizado ? " + existeAutorizado);
                    existeAutorizado = false;
                    enviaDoc = true;
                    recupera_aut = true;
                }
            }
            
            //------si el documento si tene autorizacion no entra al proceso de envio o tiene envioSRI en 0
            if (reenviaSRI.equals("0"))   {
                
                 //------si el documento tiene autorizacion no entra al proceso de envio        
                if (disponibilidad) {
                    try {

                        //---procesamos con los ws expuestos para las pruebas 
                        if (ambiente.equals("1")) {

                            urlwebService = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl";
                            CertificadosSSL.instalarCertificados();
                            EnvioComprobantesWSOFFPRU wsa = new EnvioComprobantesWSOFFPRU(urlwebService.toString().trim());                                         
                            com.gruposantorun.comprobantes.ws.pruebas.off.RespuestaSolicitud respuesta = wsa.enviarComprobante(new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaFirmada\\" + nomclave + ".xml"));
                            System.out.println("primero: " + respuesta.getEstado());

                                if (respuesta.getEstado().equals("RECIBIDA")) {
                                    //JOptionPane.showMessageDialog(this, "El documento ha sido enviada al SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                    recibido = true;
                                    envioSRI = 1;              
                                } else {
                                    recibido = false;

                                if (respuesta.getEstado().equals("DEVUELTA")) {
                                     if (existeAutorizado) {  
                                        envioSRI = 1;
                                        reenviaSRI = "1";
                                    }
                                    else
                                    {
                                        envioSRI = 0;
                                        //JOptionPane.showMessageDialog(this, "El documento no ha sido recibida por el SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                        List<com.gruposantorun.comprobantes.ws.pruebas.off.Comprobante> lst = respuesta.getComprobantes().getComprobante();
                                        System.out.println("ichi" + lst.isEmpty() );

                                            for (com.gruposantorun.comprobantes.ws.pruebas.off.Comprobante comprobante : lst) {
                                            List<com.gruposantorun.comprobantes.ws.pruebas.off.Mensaje> lstMensaje = comprobante.getMensajes().getMensaje();

                                                for (com.gruposantorun.comprobantes.ws.pruebas.off.Mensaje mensaje : lstMensaje) {
                                                    if (mensaje.getMensaje().equals("CLAVE DE ACCESO EN PROCESAMIENTO")) {
                                                        //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                       // + "\n Mensage: " + mensaje.getMensaje()
                                                       // + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                      //  + "\n Generación de contingencia...",
                                                      //  "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                        envioSRI = 0;
                                                    } else {
                                                        if (mensaje.getMensaje().equals("CLAVE ACCESO REGISTRADA")) {
                                                            envioSRI = 1;
                                                        } else {
                                                            System.out.println("estado: " + respuesta.getEstado());
                                                            System.out.println("identificador: " + mensaje.getIdentificador());
                                                            System.out.println("tipo: " + mensaje.getTipo()) ;
                                                            System.out.println("infoad: " + mensaje.getInformacionAdicional()) ;
                                                            //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                        //    + "\n Mensage: " + mensaje.getMensaje()
                                                        //    + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                        //    + "\n Generación de contingencia...",
                                                         //   "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                            envioSRI = 0;
                                                        } // fin de la clave en procesamiento
                                                    } // IF
                                                }//for
                                            }//for
                                        }//fin de else autorizado
                                    }// fin de devuelta
                                }// fin de recibida
                        }

                        //---procesamos con los ws expuestos para  el ambiente produccion 
                        if (ambiente.equals("2")) {

                            urlwebService = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl";
                            CertificadosSSL.instalarCertificados();
                            EnvioComprobantesWSOFFPRO wsa = new EnvioComprobantesWSOFFPRO(urlwebService.toString().trim());
                            com.gruposantorun.comprobantes.ws.produccion.off.RespuestaSolicitud respuesta = wsa.enviarComprobante(new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaFirmada\\" + nomclave + ".xml"));     
                  
                            System.out.println("primero: " + respuesta.getEstado());

                            if (respuesta.getEstado().equals("RECIBIDA")) {
                                //JOptionPane.showMessageDialog(this, "El documento ha sido enviada al SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                    recibido = true;
                                    envioSRI = 1;              
                                } else {
                                    recibido = false;

                                if (respuesta.getEstado().equals("DEVUELTA")) {
                                    if (existeAutorizado) {  
                                        envioSRI = 1;
                                        reenviaSRI = "1";
                                    }
                                    else
                                    {
                                        //JOptionPane.showMessageDialog(this, "El documento no ha sido recibida por el SRI: " , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                        envioSRI = 0;
                                        List<com.gruposantorun.comprobantes.ws.produccion.off.Comprobante> lst = respuesta.getComprobantes().getComprobante();
                                        System.out.println("ichi" + lst.isEmpty() );

                                            for (com.gruposantorun.comprobantes.ws.produccion.off.Comprobante comprobante : lst) {
                                            List<com.gruposantorun.comprobantes.ws.produccion.off.Mensaje> lstMensaje = comprobante.getMensajes().getMensaje();

                                                for (com.gruposantorun.comprobantes.ws.produccion.off.Mensaje mensaje : lstMensaje) {
                                                    if (mensaje.getMensaje().equals("CLAVE DE ACCESO EN PROCESAMIENTO")) {
                                                        //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                      //  + "\n Mensage: " + mensaje.getMensaje()
                                                     //   + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                     //   + "\n Generación de contingencia...",
                                                     //   "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                        envioSRI = 0;
                                                    } else {
                                                        if (mensaje.getMensaje().equals("CLAVE ACCESO REGISTRADA")) {
                                                            envioSRI = 1;
                                                        } else {
                                                            System.out.println("estado: " + respuesta.getEstado());
                                                            System.out.println("identificador: " + mensaje.getIdentificador());
                                                            System.out.println("tipo: " + mensaje.getTipo()) ;
                                                            System.out.println("infoad: " + mensaje.getInformacionAdicional()) ;
                                                            //JOptionPane.showMessageDialog(this, "ENVIO: " + respuesta.getEstado()
                                                       //     + "\n Mensage: " + mensaje.getMensaje()
                                                     //       + "\n Motivo: " + mensaje.getInformacionAdicional()
                                                       //     + "\n Generación de contingencia...",
                                                         //   "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                                            envioSRI = 0;
                                                        } // fin de la clave en procesamiento
                                                    } // IF
                                                }//for
                                            }//for
                                        }//fin de else autorizado
                                    }// fin de devuelta
                                }// fin de recibida
                        }

                    } catch (MalformedURLException ex) {
                        Logger.getLogger(FEUPW_FACT.class.getName()).log(Level.SEVERE, null, ex);
                        //JOptionPane.showMessageDialog(this, "ENVIO(MalformedURLException) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nNo se envio al SRI... ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);

                    } catch (WebServiceException ex) {
                        Logger.getLogger(FEUPW_FACT.class.getName()).log(Level.SEVERE, null, ex);
                        //JOptionPane.showMessageDialog(this, "ENVIO(WebServiceException) \nSin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\nNo se envio al Sri... ", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                    }// fin try catch  
                }
                
                
            }
        }// fin envio1 
        System.out.println("envioSRI: " +envioSRI);
        
        //----------------------si el documento esta autorizado manda a recuperar la autorizacion
        if (reenviaSRI.equals("1"))   {
            File ret_aut = new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaAutorizada\\");
            File ret_no_aut = new File("C:\\ComprobanteElectronicos\\FACTURA\\FacturaNoAutorizada\\");
            try {
                if (ambiente.equals("1")) {
                    urlwebService1 = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl";
                }
                if (ambiente.equals("2")) {
                    urlwebService1 = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl";
                }
                CertificadosSSL.instalarCertificados();
                List<String> lst_at = new ArrayList();
                AutorizacionComprobantesWS ws = new AutorizacionComprobantesWS(urlwebService1.toString().trim());
                RespuestaComprobante respuesta = ws.autorizarComprobante(nomclave);
                List<Autorizacion> lstAutorizacion = respuesta.getAutorizaciones().getAutorizacion();
                int contador = 0;
                int tam = lstAutorizacion.size();
                for (Autorizacion autorizacion : lstAutorizacion) {
                    try {
                        A aut = new A();
                        if (autorizacion.getEstado().equals("AUTORIZADO")) {
                            bandera = true;
                            band = true;
                        } 
                        contador++;
                        if (bandera && band) {
                            band = false;
                            aut.setComprobante("<![CDATA[" + autorizacion.getComprobante() + "]]>");
                            aut.setEstado(autorizacion.getEstado());
                            Calendar calendar = autorizacion.getFechaAutorizacion().toGregorianCalendar();
                            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");//yyyy/MM/dd
                            String fechaAutorizacion = sdf.format(calendar.getTime());
                            //--
                            if (ambiente.equals("1")) {
                                nomAmbiente = "PRUEBAS";
                            }

                            if (ambiente.equals("2")) {
                                nomAmbiente = "PRODUCCION";
                            }
                            
                            aut.setFechaAutorizacion(fechaAutorizacion);
                            aut.setMensajes(autorizacion.getMensajes());
                            aut.setAmbiente(nomAmbiente);
                            aut.setNumeroAutorizacion(autorizacion.getNumeroAutorizacion());

                            if (aut.getEstado().equals(estadoAutorizacion)) {
                                fecAutorizacion = aut.getFechaAutorizacion();
                                numeAutorizacion = aut.getNumeroAutorizacion();
                                estado = aut.getEstado();
                                save = true;
                                envio2 = true;
                                buscar_aut++;
                            } 
                            
                            JAXBContext jc = JAXBContext.newInstance(A.class);
                            Marshaller marshaller = jc.createMarshaller();
                            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
                            marshaller.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
                            //-------------------------------------------------------------
                            if (ret_aut.exists()) {
                                Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\FACTURA\\FacturaAutorizada\\" + nomclave + ".xml");
                                writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                writer.close();
                            } else {
                                ret_aut.mkdirs();
                                Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\FACTURA\\FacturaAutorizada\\" + nomclave + ".xml");
                                writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                writer.close();
                            }
                            /////////////////////////////////////////////////////////////////////
                            if (estado.equals("AUTORIZADO")) {
                                try {
                                    File file_server = new File(Servidor_emp);
                                    if (file_server.exists()) {
                                        Writer writer = new FileWriter(Servidor_emp + "\\" + nomclave + ".xml");
                                        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                        marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                        writer.close();
                                    } else {
                                        file_server.mkdirs();
                                        Writer writer = new FileWriter(Servidor_emp + "\\" + nomclave + ".xml");
                                        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                        marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                        writer.close();
                                    }
                                } catch (Exception ex) {
                                    //JOptionPane.showMessageDialog(this, "El directorio no existe: \n" + ex.getMessage(), "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                                }// catch ex  
                            }
                            /////////////////////////////////////////////////////////////////////// 
                        } else {
                            //JOptionPane.showMessageDialog(this, "El documento no ha sido autorizado revisar el XML en la ruta: " + ret_no_aut , "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                            if (!bandera && contador == tam) {
                                aut.setComprobante("<![CDATA[" + autorizacion.getComprobante() + "]]>");
                                aut.setEstado(autorizacion.getEstado());
                                Calendar calendar = autorizacion.getFechaAutorizacion().toGregorianCalendar();
                                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");//yyyy/MM/dd
                                String fechaAutorizacion = sdf.format(calendar.getTime());
                                //--
                                if (ambiente.equals("1")) {
                                    nomAmbiente = "PRUEBAS";
                                }

                                if (ambiente.equals("2")) {
                                    nomAmbiente = "PRODUCCION";
                                }

                                aut.setFechaAutorizacion(fechaAutorizacion);
                                aut.setMensajes(autorizacion.getMensajes());
                                aut.setAmbiente(nomAmbiente);
                                aut.setNumeroAutorizacion(autorizacion.getNumeroAutorizacion());
                                //
                                if (aut.getEstado().equals(estadoAutorizacion)) {
                                    fecAutorizacion = aut.getFechaAutorizacion();
                                    numeAutorizacion = aut.getNumeroAutorizacion();
                                    estado = aut.getEstado();
                                    save = true;
                                    envio2 = true;
                                    buscar_aut++;
                                } 
                                
                                JAXBContext jc = JAXBContext.newInstance(A.class);
                                Marshaller marshaller = jc.createMarshaller();
                                marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
                                marshaller.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
                                //-------------------------------------------------------------
                                if (ret_no_aut.exists()) {
                                    Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\FACTURA\\FacturaNoAutorizada\\" + nomclave + ".xml");
                                    writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                    marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                    writer.close();
                                } else {
                                    ret_no_aut.mkdirs();
                                    Writer writer = new FileWriter("C:\\ComprobanteElectronicos\\FACTURA\\FacturaNoAutorizada\\" + nomclave + ".xml");
                                    writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                                    marshaller.marshal(new JAXBElement<A>(new QName("autorizacion"), A.class, aut), writer);
                                    writer.close();
                                }
                            }//fin de bandera
                        }// no autorizado
                    } catch (Exception ex) {
                        //JOptionPane.showMessageDialog(this, "ENVIO(Exception) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\n Envio no realizado..!", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
                        
                    }
                }//for
            } catch (Exception ex) {
                //JOptionPane.showMessageDialog(this, "ENVIO(Exception) Sin respuesta del servidor  del SRI: \n" + ex.getMessage() + "\n Envio no realizado..!", "Aviso", //JOptionPane.INFORMATION_MESSAGE);
            }
        }// fin de recupera_aut 
        
        
        //---------------------------hacemos el insert para el fccompelec
        try {

            /////////////////////////////////////////////////////////////////////// 
            save = true;
            //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////      
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
            if (save) {
                try {
                    pruebanet bd = new pruebanet();
                    con = bd.getConexion();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    System.exit(0);
                }
                try {
                    cst = con.prepareCall("{call buscar_insertar_notaCredito_xml(?,?,?,?,?,?,?,?,?,?,?)}");
                    cst.setString(1, codemp);
                    cst.setString(2, codsuc);
                    cst.setString(3, "FA");
                    cst.setDouble(4, num);
                    cst.setDouble(5, cod);
                    cst.setString(6, nomclave);
                    cst.setString(7, nomclave);
                    cst.setString(8, fecAutorizacion);
                    cst.setString(9, estado);
                    cst.setLong(10, 2);
                    cst.setLong(11,envioSRI);
                    rs = cst.executeQuery();
                    if (rs == null) {
                    }
                    cst.close();
                    con.close();
                    FACT_SALIR.setEnabled(true);
                } catch (Exception e) {
                }
            }

        } catch (Exception e) {
            System.exit(0);
        }
        
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////   
        System.exit(0);

    }
    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void FACT_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACT_SALIRActionPerformed
        this.dispose();
    }//GEN-LAST:event_FACT_SALIRActionPerformed

    private void FACT_PROCESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACT_PROCESARActionPerformed
      
    }//GEN-LAST:event_FACT_PROCESARActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
















                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEUPW_FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FEUPW_FACT().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FACT_PROCESAR;
    private javax.swing.JButton FACT_SALIR;
    private javax.swing.JTextField empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField sucursal;
    private javax.swing.JTextField tipo_comp;
    // End of variables declaration//GEN-END:variables
}
